Update to 2.1.0 (#173)
*Issue #, if available:*

*Description of changes:*
- Update dependencies
- Fix user agent to match pom.xml
- Address new SpotBugs warnings
```
Error:  Medium: Shared primitive variable "refreshNeeded" in one thread may not yield the value of the most recent write from another thread [com.amazonaws.secretsmanager.caching.cache.SecretCacheObject] At SecretCacheObject.java:[line 207] AT_STALE_THREAD_WRITE_OF_PRIMITIVE
Error:  Low: Method intentionally throws RuntimeException. [com.amazonaws.secretsmanager.caching.cache.SecretCacheObject] At SecretCacheObject.java:[line 242] THROWS_METHOD_THROWS_RUNTIMEEXCEPTION
```
- Bump version number


By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.